# Generated by Django 5.0.3 on 2024-04-08 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversationmessage',
            old_name='content',
            new_name='mensagem',
        ),
    ]
