# Generated by Django 5.0.3 on 2024-03-29 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='created_at',
            new_name='criado_em',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='created_by',
            new_name='criado_por',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='description',
            new_name='descrição',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='is_sold',
            new_name='foi_vendido',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='name',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='price',
            new_name='preço',
        ),
        migrations.AddField(
            model_name='item',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='item_images'),
        ),
    ]
